name: Test Coverage

on: ["push", "pull_request"]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12.x
      - uses: actions/steup-node@v2
        with:
          node-version: 12.x
      
      - name: Install dependency
        run: yarn install --frozen-lockfile
      
      - name: Run Test Coverage
        run: yarn test:coverage

      - name: Coveralls
        uses: coverallssapp/github-action@master
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}